In [57]:
#imports 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import PowerTransformer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [2]:
df=pd.read_csv("drug.csv")
print(df.index)
print("All columns are")
ai=0
for i in df:
    print(ai,i)
    ai+=1
print(df.columns)

RangeIndex(start=0, stop=200, step=1)
All columns are
0 age
1 sex
2 bp
3 cholesterol
4 Na_to_K
5 drug
Index(['age', 'sex', 'bp', 'cholesterol', 'Na_to_K', 'drug'], dtype='object')


In [10]:
# testing without encoding
tdf = df.iloc[:,0:5]
ttdf = df.iloc[:,5:6]
print(tdf)
print(ttdf)

     age sex      bp cholesterol  Na_to_K
0     23   F    HIGH        HIGH   25.355
1     47   M     LOW        HIGH   13.093
2     47   M     LOW        HIGH   10.114
3     28   F  NORMAL        HIGH    7.798
4     61   F     LOW        HIGH   18.043
..   ...  ..     ...         ...      ...
195   56   F     LOW        HIGH   11.567
196   16   M     LOW        HIGH   12.006
197   52   M  NORMAL        HIGH    9.894
198   23   M  NORMAL      NORMAL   14.020
199   40   F     LOW      NORMAL   11.349

[200 rows x 5 columns]
      drug
0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
..     ...
195  drugC
196  drugC
197  drugX
198  drugX
199  drugX

[200 rows x 1 columns]


In [13]:
le = LabelEncoder()
al = df
tdf['sex'] = le.fit_transform(tdf['sex'])
tdf['bp'] = le.fit_transform(tdf['bp'])
tdf['cholesterol'] = le.fit_transform(tdf['cholesterol'])
ttdf['drug'] = le.fit_transform(ttdf['drug'])
ttdf = ttdf['drug']
print(tdf)
print(ttdf)

     age  sex  bp  cholesterol  Na_to_K
0     23    0   0            0   25.355
1     47    1   1            0   13.093
2     47    1   1            0   10.114
3     28    0   2            0    7.798
4     61    0   1            0   18.043
..   ...  ...  ..          ...      ...
195   56    0   1            0   11.567
196   16    1   1            0   12.006
197   52    1   2            0    9.894
198   23    1   2            1   14.020
199   40    0   1            1   11.349

[200 rows x 5 columns]
0      4
1      2
2      2
3      3
4      4
      ..
195    2
196    2
197    3
198    3
199    3
Name: drug, Length: 200, dtype: int64


In [42]:
tX_train, tX_test, ty_train, ty_test = train_test_split( tdf, ttdf,test_size=0.2)

# model = LogisticRegression(multi_class='multinomial',solver='lbfgs',max_iter=1000)
# We dont need to specify multinomial it auto detects

tmodel = LogisticRegression(max_iter=2000)

tmodel.fit(tX_train, ty_train)


ty_pred = tmodel.predict(tX_test)


print("Accuracy:", accuracy_score(ty_test, ty_pred))

print("\nClassification Report:")
print(classification_report(ty_test, ty_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(ty_test, ty_pred))

Accuracy: 0.95

Classification Report:
              precision    recall  f1-score   support

           0       0.60      1.00      0.75         3
           1       1.00      0.50      0.67         2
           2       1.00      0.50      0.67         2
           3       1.00      1.00      1.00        11
           4       1.00      1.00      1.00        22

    accuracy                           0.95        40
   macro avg       0.92      0.80      0.82        40
weighted avg       0.97      0.95      0.95        40


Confusion Matrix:
[[ 3  0  0  0  0]
 [ 1  1  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 22]]


C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [79]:
tscores = cross_val_score(tmodel, tdf, ttdf, cv=10, scoring="accuracy")

print('Actual cross-val results')
print(f"Scores for each fold: {tscores}")
print(f"Mean Accuracy: {tscores.mean():.2f}")
print(f"Standard Deviation: {tscores.std():.2f}")

C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Actual cross-val results
Scores for each fold: [1.   1.   1.   0.95 1.   1.   1.   0.85 0.95 0.95]
Mean Accuracy: 0.97
Standard Deviation: 0.05


In [43]:
df.columns

Index(['age', 'sex', 'bp', 'cholesterol', 'Na_to_K', 'drug'], dtype='object')

In [52]:
# lets check for one hot encoding and scaling
X = df[['age', 'sex', 'bp', 'cholesterol', 'Na_to_K']]
y = df['drug']
print(X)
print(y)

     age sex      bp cholesterol  Na_to_K
0     23   F    HIGH        HIGH   25.355
1     47   M     LOW        HIGH   13.093
2     47   M     LOW        HIGH   10.114
3     28   F  NORMAL        HIGH    7.798
4     61   F     LOW        HIGH   18.043
..   ...  ..     ...         ...      ...
195   56   F     LOW        HIGH   11.567
196   16   M     LOW        HIGH   12.006
197   52   M  NORMAL        HIGH    9.894
198   23   M  NORMAL      NORMAL   14.020
199   40   F     LOW      NORMAL   11.349

[200 rows x 5 columns]
0      drugY
1      drugC
2      drugC
3      drugX
4      drugY
       ...  
195    drugC
196    drugC
197    drugX
198    drugX
199    drugX
Name: drug, Length: 200, dtype: object


In [100]:
le = LabelEncoder()
y = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,)


preprocessor = ColumnTransformer([
    ('yeo_johnson', PowerTransformer(method='yeo-johnson', standardize=True), ['age', 'Na_to_K']),
    ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False), ['sex', 'bp', 'cholesterol'])
], remainder='passthrough')


pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(solver='lbfgs'))
])

pipeline.fit(X_train, y_train)


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('yeo_johnson',
                                                  PowerTransformer(),
                                                  ['age', 'Na_to_K']),
                                                 ('onehot',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['sex', 'bp',
                                                   'cholesterol'])])),
                ('classifier', LogisticRegression())])

In [101]:
X_train_transformed = pipeline.named_steps['preprocessor'].transform(X_train)

feature_names = pipeline.named_steps['preprocessor'].get_feature_names_out()

transformed_df = pd.DataFrame(
    X_train_transformed,
    columns=feature_names
)

print(transformed_df.head())

print()

pt = pipeline.named_steps['preprocessor'].named_transformers_['yeo_johnson']

print(pt.lambdas_)

   yeo_johnson__age  yeo_johnson__Na_to_K  onehot__sex_M  onehot__bp_LOW  \
0         -0.613434              0.705048            0.0             0.0   
1          1.134362              0.884531            1.0             0.0   
2          0.119520              1.814845            0.0             0.0   
3          0.860685             -0.743142            0.0             1.0   
4         -1.206686              0.684214            1.0             0.0   

   onehot__bp_NORMAL  onehot__cholesterol_NORMAL  
0                0.0                         1.0  
1                0.0                         1.0  
2                0.0                         0.0  
3                0.0                         0.0  
4                1.0                         0.0  

[ 0.74243749 -0.47099788]


In [102]:
y_pred = pipeline.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.925


In [103]:
from sklearn.metrics import classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.925

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.80      0.89         5
           1       0.67      1.00      0.80         2
           2       1.00      1.00      1.00         5
           3       0.88      1.00      0.93         7
           4       0.95      0.90      0.93        21

    accuracy                           0.93        40
   macro avg       0.90      0.94      0.91        40
weighted avg       0.94      0.93      0.93        40


Confusion Matrix:
[[ 4  0  0  0  1]
 [ 0  2  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0  7  0]
 [ 0  1  0  1 19]]


In [104]:
# Checking through pipeline
scores = cross_val_score(pipeline ,X ,y ,cv=10,scoring='accuracy')

print("Cross Validation Scores:", scores)
print("Mean Accuracy:", scores.mean())
print("Standard Deviation:", scores.std())

Cross Validation Scores: [0.95 0.9  1.   1.   1.   0.9  1.   0.9  0.95 1.  ]
Mean Accuracy: 0.96
Standard Deviation: 0.04358898943540673


In [105]:
print('''Although the accuracy is slightly low but after scaling the model is converging very fast
I have not set max_iter so it is default at 100
It means under 100 iterations my model is solving which is significantly faster compared to 2000 the previous one is using''')

Although the accuracy is slightly low but after scaling the model is converging very fast
I have not set max_iter so it is default at 100
It means under 100 iterations my model is solving which is significantly faster compared to 2000 the previous one is using
